"""Update game

Revision ID: 1176c7b3c1ba
Revises: af987209f4b6
Create Date: 2019-06-01 18:18:35.956316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1176c7b3c1ba'
down_revision = 'af987209f4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
