"""Add game and move

Revision ID: 1458f7d067e1
Revises: fc00de365f98
Create Date: 2019-06-01 17:08:00.258068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1458f7d067e1'
down_revision = 'fc00de365f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
