"""Add game and move columns

Revision ID: 41f9b9147fc8
Revises: d946a140fee6
Create Date: 2019-06-01 17:14:51.633412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f9b9147fc8'
down_revision = 'd946a140fee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
