"""test

Revision ID: 7e73f1632630
Revises: f4165efa82f3
Create Date: 2019-06-01 18:31:08.795329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e73f1632630'
down_revision = 'f4165efa82f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
