"""add user_game_table

Revision ID: a3618a88d84b
Revises: c42160bee344
Create Date: 2019-06-01 17:59:10.192714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3618a88d84b'
down_revision = 'c42160bee344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
