"""Some update

Revision ID: af987209f4b6
Revises: a3618a88d84b
Create Date: 2019-06-01 18:11:05.216992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af987209f4b6'
down_revision = 'a3618a88d84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
