"""Add game and move columns

Revision ID: c42160bee344
Revises: 41f9b9147fc8
Create Date: 2019-06-01 17:15:38.296865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42160bee344'
down_revision = '41f9b9147fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
