"""Test changes 1

Revision ID: f4165efa82f3
Revises: 3e42872b605d
Create Date: 2019-06-01 18:27:52.770120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4165efa82f3'
down_revision = '3e42872b605d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('move', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'move', 'game', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'move', type_='foreignkey')
    op.drop_column('move', 'game_id')
    # ### end Alembic commands ###
