"""Update relationships

Revision ID: fc00de365f98
Revises: e17b0296bd76
Create Date: 2019-06-01 13:52:25.579042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc00de365f98'
down_revision = 'e17b0296bd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
